name: Publish to NPM
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
      - name: Publish package on NPM 📦
        run: npm publish
        working-directory: ./packages/component
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
